// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ListarTasksResponse, CriarTaskData, CriarTaskResponse, AtualizarTaskData, AtualizarTaskResponse, DeletarTaskData, DeletarTaskResponse, ListarTagsResponse, CriarTagData, CriarTagResponse, DeletarTagData, DeletarTagResponse } from './types.gen';

export class TarefasService {
    /**
     * Listar Tasks
     * @returns TaskSchema OK
     * @throws ApiError
     */
    public static listarTasks(): CancelablePromise<ListarTasksResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/tasks'
        });
    }
    
    /**
     * Criar Task
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static criarTask(data: CriarTaskData): CancelablePromise<CriarTaskResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/tasks',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Atualizar Task
     * @param data The data for the request.
     * @param data.taskId
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static atualizarTask(data: AtualizarTaskData): CancelablePromise<AtualizarTaskResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/tasks/{task_id}',
            path: {
                task_id: data.taskId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Deletar Task
     * @param data The data for the request.
     * @param data.taskId
     * @returns unknown OK
     * @throws ApiError
     */
    public static deletarTask(data: DeletarTaskData): CancelablePromise<DeletarTaskResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/tasks/{task_id}',
            path: {
                task_id: data.taskId
            }
        });
    }
    
    /**
     * Listar Tags
     * @returns TagSchema OK
     * @throws ApiError
     */
    public static listarTags(): CancelablePromise<ListarTagsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/tags'
        });
    }
    
    /**
     * Criar Tag
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TagSchema OK
     * @throws ApiError
     */
    public static criarTag(data: CriarTagData): CancelablePromise<CriarTagResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/tags',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Deletar Tag
     * @param data The data for the request.
     * @param data.tagId
     * @returns unknown OK
     * @throws ApiError
     */
    public static deletarTag(data: DeletarTagData): CancelablePromise<DeletarTagResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/tags/{tag_id}',
            path: {
                tag_id: data.tagId
            }
        });
    }
    
}