// This file is auto-generated by @hey-api/openapi-ts

export type TagSchema = {
    nome: string;
};

export type TaskCreateSchema = {
    titulo: string;
    status_id?: (number | null);
    descricao?: (string | null);
};

export type TaskSchema = {
    id: number;
    titulo: string;
    status_id: (number | null);
    descricao?: (string | null);
};

export type TaskUpdateSchema = {
    titulo: string;
    descricao?: (string | null);
    status_id?: (number | null);
};

export type ListarTasksResponse = (Array<TaskSchema>);

export type CriarTaskData = {
    requestBody: TaskCreateSchema;
};

export type CriarTaskResponse = (unknown);

export type AtualizarTaskData = {
    requestBody: TaskUpdateSchema;
    taskId: number;
};

export type AtualizarTaskResponse = (unknown);

export type DeletarTaskData = {
    taskId: number;
};

export type DeletarTaskResponse = (unknown);

export type ListarTagsResponse = (Array<TagSchema>);

export type CriarTagData = {
    requestBody: TagSchema;
};

export type CriarTagResponse = (TagSchema);

export type DeletarTagData = {
    tagId: number;
};

export type DeletarTagResponse = (unknown);