# Generated by Django 5.1.5 on 2025-02-09 22:31

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=core.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, to='core.status'),
        ),
    ]
