# Generated by Django 5.1.5 on 2025-02-09 22:34

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=core.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.status'),
        ),
    ]
